# Running the nf-core/rnaseq pipeline v3.23.0

We will not process the original dataset because more computing power would be required. Instead, we will process only two size-reduced samples where 50,000 reads were randomly sampled from the original data (used script for sub-sampling: `util/subsample_50k_PRJNA1158806.sh`).

We will use pipeline release [v3.23.0](https://nf-co.re/rnaseq/3.23.0). From this release, it is possible to use Bowtie2 for read alignment, which is advantageous for processing prokaryotic RNAseq data. For simplicity, we specify a "prokaryotic" profile which automatically uses Bowtie2 for read alignment and Salmon for read quantification.

**To process the data, run the following command:**

```bash
nextflow run 'https://github.com/nf-core/rnaseq' \
    -name 'Ecoli_MG1655_saccharin_2_samples' \
    --outdir '/workspaces/dsp_transcriptomics_training/results/nfcore_rnaseq_processing_subsampled' \
    --input '/workspaces/dsp_transcriptomics_training/data/seq_files_subsampled/samplesheet_50k_subsampled_2samples.csv' \
    --fasta '/workspaces/dsp_transcriptomics_training/data/genome_files/GCF_000005845.2_ASM584v2_genomic.fna.gz' \
    --gtf '/workspaces/dsp_transcriptomics_training/data/genome_files/GCF_000005845.2_ASM584v2_genomic.gtf.gz' \
    -r 3.23.0 \
    -profile prokaryotic,docker \
    -c /workspaces/dsp_transcriptomics_training/01_scripts/custom.config
```

**Parameter descriptions:**

-   `-name`: name of the processing run
-   `--outdir`: (absolute) path to the output directory where results will be saved (the sub-directory is created automatically)
-   `--input`: (absolute) path to the sample sheet
-   `--fasta`: (absolute) path to the gzipped genome FASTA file
-   `--gtf`: (absolute) path to the gzipped genome annotation file
-   `-r`: nf-core/rnaseq pipeline release/version
-   `-profile`: profile(s) to run; here "prokaryotic" mode using "docker"
-   `-c`: (absolute) path to the custom configuration file; used here to limit the number of CPUs and memory

The Nextflow command is stored in a bash script and can be executed by running:

```bash
bash 01_scripts/00_nfcore_rnaseq_processing.sh
```

The processing time is about 7 minutes.

<div class="remember">
  <strong>📌 Remember:</strong> Rather than configuring parameters manually, nf-core offers automatic parameter configuration. Go to the [pipeline page](https://nf-co.re/rnaseq/3.23.0) and press **Launch version 3.23.0** to see all pipeline parameters and change them as needed. A configuration file can be generated automatically for use with your Nextflow command.
</div>

## Structure of the output directory

The results of the pipeline run will be saved in `results/nfcore_rnaseq_processing_subsampled`. The top-level folder structure is as follows:

```
.
├── bowtie2_salmon
├── fastqc
├── fq_lint
├── multiqc
├── pipeline_info
└── trimgalore
```

The detailed structure of the output directory:

```
.
├── bowtie2_salmon
│   ├── control_1
│   │   ├── aux_info
│   │   ├── cmd_info.json
│   │   ├── libParams
│   │   ├── logs
│   │   ├── quant.genes.sf
│   │   └── quant.sf
│   ├── control_1.markdup.sorted.bam
│   ├── control_1.markdup.sorted.bam.bai
│   ├── deseq2_qc
│   │   ├── deseq2.dds.RData
│   │   ├── deseq2.pca.vals.txt
│   │   ├── deseq2.plots.pdf
│   │   ├── deseq2.sample.dists.txt
│   │   ├── R_sessionInfo.log
│   │   └── size_factors
│   ├── log
│   │   ├── control_1.bowtie2.log
│   │   └── saccharin_1.bowtie2.log
│   ├── picard_metrics
│   │   ├── control_1.markdup.sorted.MarkDuplicates.metrics.txt
│   │   └── saccharin_1.markdup.sorted.MarkDuplicates.metrics.txt
│   ├── saccharin_1
│   │   ├── aux_info
│   │   ├── cmd_info.json
│   │   ├── libParams
│   │   ├── logs
│   │   ├── quant.genes.sf
│   │   └── quant.sf
│   ├── saccharin_1.markdup.sorted.bam
│   ├── saccharin_1.markdup.sorted.bam.bai
│   ├── salmon.merged.gene_counts_length_scaled.tsv
│   ├── salmon.merged.gene_counts_scaled.tsv
│   ├── salmon.merged.gene_counts.tsv
│   ├── salmon.merged.gene_lengths.tsv
│   ├── salmon.merged.gene.SummarizedExperiment.rds
│   ├── salmon.merged.gene_tpm.tsv
│   ├── salmon.merged.transcript_counts.tsv
│   ├── salmon.merged.transcript_lengths.tsv
│   ├── salmon.merged.transcript.SummarizedExperiment.rds
│   ├── salmon.merged.transcript_tpm.tsv
│   ├── salmon.merged.tx2gene.tsv
│   ├── samtools_stats
│   │   ├── control_1.markdup.sorted.bam.flagstat
│   │   ├── control_1.markdup.sorted.bam.idxstats
│   │   ├── control_1.markdup.sorted.bam.stats
│   │   ├── control_1.sorted.bam.flagstat
│   │   ├── control_1.sorted.bam.idxstats
│   │   ├── control_1.sorted.bam.stats
│   │   ├── saccharin_1.markdup.sorted.bam.flagstat
│   │   ├── saccharin_1.markdup.sorted.bam.idxstats
│   │   ├── saccharin_1.markdup.sorted.bam.stats
│   │   ├── saccharin_1.sorted.bam.flagstat
│   │   ├── saccharin_1.sorted.bam.idxstats
│   │   └── saccharin_1.sorted.bam.stats
│   └── stringtie
│       ├── control_1.ballgown
│       ├── control_1.coverage.gtf
│       ├── control_1.gene.abundance.txt
│       ├── control_1.transcripts.gtf
│       ├── saccharin_1.ballgown
│       ├── saccharin_1.coverage.gtf
│       ├── saccharin_1.gene.abundance.txt
│       └── saccharin_1.transcripts.gtf
├── fastqc
│   ├── raw
│   │   ├── control_1_raw_1_fastqc.html
│   │   ├── control_1_raw_1_fastqc.zip
│   │   ├── control_1_raw_2_fastqc.html
│   │   ├── control_1_raw_2_fastqc.zip
│   │   ├── saccharin_1_raw_1_fastqc.html
│   │   ├── saccharin_1_raw_1_fastqc.zip
│   │   ├── saccharin_1_raw_2_fastqc.html
│   │   └── saccharin_1_raw_2_fastqc.zip
│   └── trim
│       ├── control_1_trimmed_1_val_1_fastqc.html
│       ├── control_1_trimmed_1_val_1_fastqc.zip
│       ├── control_1_trimmed_2_val_2_fastqc.html
│       ├── control_1_trimmed_2_val_2_fastqc.zip
│       ├── saccharin_1_trimmed_1_val_1_fastqc.html
│       ├── saccharin_1_trimmed_1_val_1_fastqc.zip
│       ├── saccharin_1_trimmed_2_val_2_fastqc.html
│       └── saccharin_1_trimmed_2_val_2_fastqc.zip
├── fq_lint
│   ├── raw
│   │   ├── control_1.fq_lint.txt
│   │   └── saccharin_1.fq_lint.txt
│   └── trimmed
│       ├── control_1.fq_lint.txt
│       └── saccharin_1.fq_lint.txt
├── multiqc
│   └── bowtie2_salmon
│       ├── multiqc_report_data
│       ├── multiqc_report.html
│       └── multiqc_report_plots
├── pipeline_info
│   ├── execution_report_2026-05-15_15-41-45.html
│   ├── execution_timeline_2026-05-15_15-41-45.html
│   ├── execution_trace_2026-05-15_15-41-45.txt
│   ├── nf_core_rnaseq_software_mqc_versions.yml
│   ├── params_2026-05-15_15-42-05.json
│   └── pipeline_dag_2026-05-15_15-41-45.html
└── trimgalore
    ├── control_1_trimmed_1.fastq.gz_trimming_report.txt
    ├── control_1_trimmed_2.fastq.gz_trimming_report.txt
    ├── saccharin_1_trimmed_1.fastq.gz_trimming_report.txt
    └── saccharin_1_trimmed_2.fastq.gz_trimming_report.txt
```


## Interpretation of RNAseq processing results using the multiQC report

The nf-core/rnaseq pipeline generates a multiQC report which consolidates all quality control (QC) metrics from the pipeline run.  
We will be analyzing the [multiQC report from processing the entire dataset](https://github.com/biosustain/dsp_transcriptomics_training/tree/main/results/multiqc_nfcore_rnaseq_full_dataset/multiQC_Ecoli_sac_ctrl_deDios_2025_full_dataset.html) - which we have done prior to this course - rather than the one generated in your test run.  

The multiQC reports summarizes important QC metrics from RNAseq data processing. This includes for example:

- Tabular overview of general statistics
- QC metrics from FastQC and other software tools, e.g. read quality scores, GC and adaptor content before and after read trimming, % duplication, % read alignmnt, etc
- PCA plot and Euclidean distance heatmap
- Versions of the software tools used (see the end of the report)


Please take a few minutes to inspect the multiQC report, list your observations and questions, and try to find explanations for the observations made. You can use the left panel for navigating the report. We will discuss your findings and questions afterwards.  

:::boxy
The three control samples are ```C1```, ```C2``` and ```C3```.  
The three saccharin treatment samples are ```sac1```, ```sac2```and ```sac3```.
:::

For example, you could pay attention to the details of the following:

<div class="question">
  <strong>❓ Question:</strong> How is are the per base quality scores?
</div>

- see ```Sequence Quality Histograms before and after trimming```

<div class="question">
  <strong>❓ Question:</strong> There is a maximum of 85% aligned reads? What could be the reason(s)?
</div>

- see the ```General Statistics``` section

<div class="question">
  <strong>❓ Question:</strong> Why is the percentage of aligned reads lower in C1 and C2 compared o all other samples?
</div>

- see the ```General Statistics``` section, ```Per Sequence GC Content before and after trimming``` and ```Top overrepresented sequences```and ```Adaptor content```

<div class="question">
  <strong>❓ Question:</strong> Insepct the duplication level of reads. What could duplication stem from and how to treat it?
</div>

- see the ```General Statistics``` section, ```Fastq Sequence Counts```, ```Picard Mark duplicates```

<div class="question">
  <strong>❓ Question:</strong> - How do the samples cluster? (see ```BOWTIE2_SALMON DESeq2 PCA plot and sample similarity```)
</div>
