FROM mcr.microsoft.com/devcontainers/base:noble

RUN apt-get update && apt-get install -y \
  build-essential \
  gfortran \
  libblas-dev \
  libcairo2-dev \
  libcurl4-openssl-dev \
  libfontconfig1-dev \
  libfreetype6-dev \
  libfribidi-dev \
  libglib2.0-dev \
  libharfbuzz-dev \
  libjpeg-dev \
  liblapack-dev \
  libnlopt-dev \
  libpng-dev \
  libssl-dev \
  libtiff5-dev \
  libxml2-dev \
  pkg-config \
  r-base-dev
